version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # restart: on-failure
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules

  backend:
    build:
      context: ./backend  
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: on-failure
    ports:
      - "5432:5432"
    env_file:
      - ./backend/.env
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: